version: '3.7'

services:
  redis:
    image: "redis:alpine"
    container_name: capif-redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  api-invoker-management:
    container_name: api-invoker-management
    build: TS29222_CAPIF_API_Invoker_Management_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_API_Invoker_Management_API:/usr/src/app
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/capif/api_invoker_management_api:latest
    depends_on:
    - redis
    - nginx
  api-provider-management:
    container_name: api-provider-management
    build: TS29222_CAPIF_API_Provider_Management_API/.
    expose:
      - "8080"
    image: dockerhub.hi.inet/fogus-services/capif/api_provider_management_api:latest
    depends_on:
      - redis
      - nginx
  logs:
    container_name: capif-auditing
    build: TS29222_CAPIF_Auditing_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Auditing_API:/usr/src/app
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/capif/auditing_api:latest
  service-apis:
    container_name: service-apis
    build: TS29222_CAPIF_Discover_Service_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Discover_Service_API:/usr/src/app
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/capif/discover_service_api:latest
    depends_on:
    - mongo
  capif-events:
    container_name: capif-events
    build: TS29222_CAPIF_Events_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Events_API:/usr/src/app
    image: dockerhub.hi.inet/fogus-services/capif/events_api:latest
    depends_on:
      - redis
      - mongo
  api-invocation-logs:
    container_name: capif-logging
    build: TS29222_CAPIF_Logging_API_Invocation_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Logging_API_Invocation_API:/usr/src/app
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/capif/api_invocation_logs_api:latest
    environment:
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
  published-apis:
    container_name: published-apis
    build: TS29222_CAPIF_Publish_Service_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Publish_Service_API:/usr/src/app
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/capif/publish_service_api:latest
    depends_on:
      - redis
      - mongo
  capif-routing-info:
    container_name: capif-routing-info
    build: TS29222_CAPIF_Routing_Info_API/.
    expose:
      - "8080"
    image: dockerhub.hi.inet/fogus-services/capif/routing_info_api:latest
  capif-security:
    container_name: capif-security
    build: TS29222_CAPIF_Security_API/.
    expose:
      - "8080"
    volumes:
      - ./TS29222_CAPIF_Security_API:/usr/src/app
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/capif/security_api:latest
    environment:
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - redis
      - nginx
  easy-rsa:
    container_name: capif-ca
    build:
      context: ./easy_rsa
    expose:
      - "8080"
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/easy-rsa:latest
  jwtauth:
    container_name: capif-jwtauth
    build:
      context: ./jwt_auth
    expose:
      - "8080"
    volumes:
      - ./jwt_auth:/usr/src/app
    restart: unless-stopped
    image: dockerhub.hi.inet/fogus-services/jwtauth:latest
    depends_on:
      - easy-rsa
      - mongo
      - redis
      - nginx
  mongo:
    container_name: capif-mongo
    image: mongo:6.0.2
    logging:
      driver: 'none'
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    container_name: capif-mongo-express
    image: mongo-express:1.0.0-alpha.4
    logging:
      driver: 'none'
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  nginx:
    container_name: capif-nginx
    build:
      context: ./nginx
    ports:
      - "8080:8080"
      - "443:443"
    image: dockerhub.hi.inet/fogus-services/capif/nginx:latest
    environment:
      - CAPIF_HOSTNAME=${CAPIF_HOSTNAME}
    hostname: ${CAPIF_HOSTNAME}
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    restart: unless-stopped
    depends_on:
      - easy-rsa
      - redis
      - service-apis
      - api-invocation-logs
      - published-apis
      - capif-events
      - logs


